#ifndef SAILINGBOAT_INCLUDE_DATACONTAINERS_GPS_POSITION_H_
#define SAILINGBOAT_INCLUDE_DATACONTAINERS_GPS_POSITION_H_

class GPSPosition {
 public:
  GPSPosition();
  double latitude;
  double longitude;
};

#endif // SAILINGBOAT_INCLUDE_DATACONTAINERS_GPS_POSITION_H_
